In [1]:
from tensorflow.keras.datasets import mnist

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
from tensorflow.keras.utils import to_categorical

In [19]:
from tensorflow.keras import models, layers

In [4]:
import matplotlib.pyplot as plt

In [5]:
(trainX, trainY),(testX,testY) = mnist.load_data()

In [6]:
trainX.shape

(60000, 28, 28)

In [7]:
testY.shape

(10000,)

In [8]:
predX = testX[9990:]
predY = testY[9990:]
testX = testX[:9990]
testY = testY[:9990]

In [9]:
testY.shape

(9990,)

In [10]:
trainX.shape

(60000, 28, 28)

In [11]:
trainX = trainX.reshape(60000,28*28)
testX = testX.reshape(9990,28*28)

In [12]:
trainX.shape

(60000, 784)

In [13]:
trainX

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [14]:
trainX[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,  18,  18,
       126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 17

In [15]:
trainX = trainX.astype('float32')/255
testX = testX.astype('float32')/255

In [16]:
trainX[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [17]:
trainY[0:15]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4, 3, 5, 3, 6, 1], dtype=uint8)

In [18]:
trainY = to_categorical(trainY)
testY = to_categorical(testY)

In [22]:
def mnist():
    model = models.Sequential()
    model.add(layers.Dense(512, activation='relu', input_shape=(28*28,)))
    model.add(layers.Dense(10, activation='softmax'))
    model.compile(optimizer = 'rmsprop', loss = 'categorical_crossentropy', metrics = ['accuracy'])
    return model

In [23]:
model = mnist()

In [24]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 512)               401920    
_________________________________________________________________
dense_2 (Dense)              (None, 10)                5130      
Total params: 407,050
Trainable params: 407,050
Non-trainable params: 0
_________________________________________________________________


In [27]:
model.fit(trainX,trainY, epochs = 10, batch_size = 128)

Train on 60000 samples
Epoch 1/10
60000/60000 [==============================] - 4s 75us/sample - loss: 2.9924e-04 - accuracy: 0.9999
Epoch 2/10
60000/60000 [==============================] - 5s 76us/sample - loss: 3.4551e-04 - accuracy: 0.9999
Epoch 3/10
60000/60000 [==============================] - 5s 76us/sample - loss: 2.4640e-04 - accuracy: 0.9999
Epoch 4/10
60000/60000 [==============================] - 5s 77us/sample - loss: 2.3499e-04 - accuracy: 0.9999
Epoch 5/10
60000/60000 [==============================] - 5s 77us/sample - loss: 1.5469e-04 - accuracy: 1.0000
Epoch 6/10
60000/60000 [==============================] - 5s 78us/sample - loss: 1.2657e-04 - accuracy: 1.0000
Epoch 7/10
60000/60000 [==============================] - 5s 77us/sample - loss: 1.8634e-04 - accuracy: 0.9999
Epoch 8/10
60000/60000 [==============================] - 5s 78us/sample - loss: 4.2825e-05 - accuracy: 1.0000
Epoch 9/10
60000/60000 [==============================] - 5s 79us/sample - loss: 6.1295e-

In [28]:
test_loss, test_accuracy = model.evaluate(testX,testY)
test_loss
test_accuracy

9990/1 [================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

0.9831832